# Use a Python 3 base image
FROM python:3

# Install MySQL client
RUN apt-get update && \
    apt-get install -y

RUN apt-get install -y default-mysql-client &&\
    apt-get install -y default-mysql-server &&\
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements.txt and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt



# Copy your Python application code
COPY . .

# install api_keys to environ var
COPY .api_keys.env .
RUN /bin/bash -c "source .api_keys.env || true"


# Run the mysql script
# RUN cat models/engine/db.sql | mariadb -u root

# Set up environment variables
ENV MYSQL_HOST=localhost \
    MYSQL_USER=root \
    MYSQL_PASSWORD=secret \
    MYSQL_DATABASE=mydatabase
    
# Expose port 5000
EXPOSE 5000

# Define the command to run your application
CMD ["bash"]
